var GAME_LEVELS = [
  ["                                                                                ",
   "            y         y         y         y         y         y         y       ",
   "       y         y         y         y         y         y         y         y  ",
   "                                                                                ",
   "                                                                   o            ",
   "                                                    o                   o       ",
   "                                                                  xxx           ",
   "                                                   x x     xx    xx!xx   o      ",
   "                                     oo      xx                  x!!!x          ",
   "                                                       xx        xx!xx    o     ",
   "                                   xxxxx                          xvx           ",
   "                                                                           xxx  ",
   "  xx                                       oo                                x  ",
   "  x           oo       o                                                     x  ",
   "  x                                      xxxxx                             g x  ",
   "  x          xxxx                                                            x  ",
   "  x  @       x  x                    xxx        xxx              xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxx xxxxxx  xx                   xx   xxxxxxxx   xxxx  xxx  ",
   "                      x x    x                            x             x  x    ",
   "                      x!x    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x             x!!x    ",
   "                      x!x    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x             x!!x    ",
   "                      xxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             xxxx    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                              g  xxxxxxxx                                    x!x  ",
   "                                                                        xxxx                                 x!x  ",
   "                                      xxxxxxxxxxxxxx          x            xx                                x!x  ",
   "                                 xx   xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                           xx                   xx!x         x     o   o                                    xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                 xxx                xx           xvxxx       x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                xx!xx                                x       xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                x!!!x          xx                    x       x!!!!!!!!!!!!!xx            v                        ",
   "                xx!xx                  xx            x       xvxxxx!!!!!xxxx                                      ",
   "                 xvx                           x    xx            xxxxxxx        xxx         xxx                  ",
   "                                               x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             xx        x                    ",
   "                  o                            xx    x                             x         x                    ",
   "                                               x     x      o  o     x   x         x         x                    ",
   "                              xxx   xxx        x     x               x   x         x         x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x          x    xx               x   x   x               x                    ",
   "     @       x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x    x    x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x!!!!!!!!!x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["   y                             xxx                                                                      y   ",
   "       y                         x!x                                                                   y      ",
   "   y                             xvx                                                                      y   ",
   "       y                                                                                              y       ",
   "   y                                                                                                      y   ",
   "       y                                o                                                             y       ",
   "   y                                                                                                      y   ",
   "       y                                x                                                             y       ",
   "   y                                    x                                                                 y   ",
   "       y                                x                                                             y       ",
   "   y                                    x                                                                 y   ",
   "       y                               xxx                                                            y       ",
   "   y                                   x x                 !!!        !!!  xxx                            y   ",
   "       y                               x x                 !x!        !x!                             y       ",
   "   y                                 xxx xxx                x          x                                  y   ",
   "       y                              x   x                 x   oooo   x       xxx                    y       ",
   "   y                          x       x   x                 x          x      x!!!x                       y   ",
   "       y                              x   x                 xxxxxxxxxxxx       xxx                    y       ",
   "   y                                 xx   xx      x   x      x                                            y   ",
   "       y                              x   xxxxxxxxx   xxxxxxxx              x x                        y      ",
   "   y                          x       x   x           x                    x!!!x                          y   ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x             o                         ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                          xxxxx  xx  xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                          xxxxxxxxxxxxxxxx x          x!!!!!!!!!!!!!!x                                        ",
   "                        oxx                x   xxxxxxxxxxxxxxxxxxxxxxx                                    g   ",
   "                        xxx               xx                                         xxx                      ",
   "  xxx                  xx!x               x                                         x!!!x                xxx  ",
   "  x x                   !!x               x                                          xxx                 x x  ",
   "  x                  xx!!!x               xxxxxxx                        xxxxx                             x  ",
   "  x                o  !!!!x               x                              x   x                      xx     x  ",
   "  x                xx!!!!!x               x                              x x x                             x  ",
   "  x                 !!!!!!x               x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x              xx!!!!!!!x               x                              x         xxx                     x  ",
   "  x            o  !!!!!!!!x               x                             xxx       x!!!x          x         x  ",
   "  x            xx!!!!!!!!!x               x                             x x        xxx          xxx        x  ",
   "  x             !!!!!!!!!!x                  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @   xx!!!!!!!!!!!x               x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["   y         y         y         y         y         y        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "        y         y         y         y         y         y        |     |     |     |     |      x           ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                           x       ",
   "                                                                                             o o o    x       ",
   "                   xxx                                                           =                  p x       ",
   "       !  o  !                                                  xxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                   x x   x x   x x   x x   x x   x x            ",
   "       x= o  x            x                                    xx!x!xxx!x!xxx!x!xxx!x!xxx!x!xxx!x!xxxxx       ",
   "       x     x                                                  x!x!!!x!x!!!x!x!!!x!x!!!x!x!!!x!x!!!!!x       ",
   "       !  o  !            o                                  xxxxvxxxxxvxxxxxvxxxxxvxxxxxvxxxxxvxxxxxxx       ",
   "                                                          o                                                   ",
   "          o              xxx                              xx                                                  ",
   "                         x!x                                                                                  ",
   "                         xvx                                                                                  ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                    v           v                                                                         g   ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                       x   ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "      g             x           x                                ||                                   x       ",
   "  xxxxxxxxxxx      xxx         xxx                                                                   xx       ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x         xxx       ",
   "  x         x   x       x   x       x   x                 ||                  x     x              xxxx       ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                         xxxxx       ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                      xxxxxx       ",
   "        x=                  =                =x   x                     xxx                     xxxxxxx       ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["                                                                      ",
   "                                                                      ",
   "         x         x     xxxxxx       x           x                   ",
   "          x       x     x      x      x           x                   ",
   "           x     x     x    |   x     x           x                   ",
   "            x   x     x          x    x           x                   ",
   "             x x      x    =     x    x           x                   ",
   "              x       x          x    x           x                   ",
   "              x        x        x      x         x                    ",
   "              x         x      x        x       x                     ",
   "              x          xxxxxx          xxxxxxx                      ",
   "                                                                      ",
   "         x    x    x     xxxxxx      xx        x        x  x          ",
   "         x    x    x       xx        x x       x        x  x          ",
   "         x    x    x       xx        x  x      x        x  x          ",
   "         x    x    x       xx        x   x     x        x  x          ",
   "         x    x    x       xx        x    x    x        x  x          ",
   "         x    x    x       xx        x     x   x        x  x          ",
   "         x    x    x       xx        x      x  x        x  x          ",
   "         x    x    x       xx        x       x x                      ",
   "         xxxxxxxxxxx     xxxxxx      x        xx        x  x          ",
   "                                                                      ",
   "  @  g                                                                ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
